validate:
  email_max_length: 255
  name_max_length: 255
  min_length_password: 6
  content_max_length: 50
settings:
  per_page: 4
  remember: 1
  limit_product: 12
  limit_product_slibar: 3
  max_value_input: 1
  max_size_image: 5
  min_role: 1
  max_role: 2
  max_value_address: 100
  min_value_address: 4
